@startuml

class SingletonLog {
  {static} -instance:SingletonLog
  -cont : int
  -SingletonLog()
  -lista : List<int>
  {static} +getInstance():Log
  +QtdAcesso(): int
  +getLog(): List<int>
}
SingletonLog -up-> SingletonLog 

class Cliente {
    +Main(): void
}
Cliente..> SingletonLog
@endumln